### ISSUE TITLE
RobotBuilder not published to development on maven

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/build-tools#44]
Last file in http://first.wpi.edu/FRC/roborio/maven/development/edu/wpi/first/wpilib/RobotBuilder/ is from 2016. Release is fine.

**Comment by ThadHouse** [comment]
Looking through, this is actually 2 issues. The first is the RobotBuilder UI tests are failing on jenkins. And the second is the RobotBuilder gradle file doesn't setup the wpilib plugin properly. I'll PR the second issue, but @sciencewhiz how do you think we should solve the first issue?

https://frcjenkins.wpi.edu/job/RobotBuilder/job/RobotBuilder%20-%20Development/23/console

**Comment by sciencewhiz** [comment]
Didn’t shuffleboard go through something similar recently?

**Comment by ThadHouse** [comment]
They might have. I'll ask them.

**Comment by sciencewhiz** [comment]
Fixed by #45 and wpilibsuite/RobotBuilder#70
